//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopify_ZeinIbrahim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string SKUID { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> CurrentStock { get; set; }
        public Nullable<decimal> minimumAllowedStock { get; set; }
        public string Warehouse { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
